2022-04-06 18:03:58,389 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:03:58,391 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:03:58,391 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:03:58,391 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:03:58,391 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:03:58,392 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:03:58,392 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.jpg', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.jpg'>, 'image/jpg')}
2022-04-06 18:03:58,394 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:11:48,642 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:11:48,642 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:11:48,643 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:11:48,643 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:11:48,643 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:11:48,643 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:11:48,643 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.jpg', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.jpg'>, 'image/jpg')}
2022-04-06 18:11:48,645 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:16:50,863 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:16:50,864 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.jpg', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.jpg'>, 'image/jpg')}
2022-04-06 18:16:50,867 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:18:33,940 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:18:33,940 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:18:33,940 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:18:33,940 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:18:33,940 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:18:33,941 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:18:33,941 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.jpg', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.jpg'>, 'image/jpg')}
2022-04-06 18:18:33,942 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:21:25,377 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:21:25,378 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.png', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.png'>, 'image/png')}
2022-04-06 18:21:25,381 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:29:01,635 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:29:01,637 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.png', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.png'>, 'image/png')}
2022-04-06 18:29:01,642 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022-04-06 18:31:03,862 DEBUG [apiautotest] [client.py (send:44] - 接口的url是：None
2022-04-06 18:31:03,862 DEBUG [apiautotest] [client.py (send:44] - 接口的method是：post
2022-04-06 18:31:03,862 DEBUG [apiautotest] [client.py (send:44] - 接口的headers是：None
2022-04-06 18:31:03,862 DEBUG [apiautotest] [client.py (send:44] - 接口的params是：{'scence': 'goods'}
2022-04-06 18:31:03,862 DEBUG [apiautotest] [client.py (send:44] - 接口的data是：None
2022-04-06 18:31:03,863 DEBUG [apiautotest] [client.py (send:44] - 接口的json是：None
2022-04-06 18:31:03,863 DEBUG [apiautotest] [client.py (send:44] - 接口的files是：{'file': ('logo.png', <_io.BufferedReader name='/Users/ninghui/Documents/M/code/apistudy/apiframwork/data/logo.png'>, 'image/png')}
2022-04-06 18:31:03,863 ERROR [apiautotest] [client.py (send:50] - 接口发起异常
Traceback (most recent call last):
  File "/Users/ninghui/Documents/M/code/apistudy/apiframwork/common/client.py", line 46, in send
    self.resp = self.session.request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
